name: Prettify Code

on:
  push:
    branches:
      - main

jobs:
  prettier:
    if: "!startsWith(github.event.head_commit.message, 'chore: prettify code')"
    runs-on: ubuntu-latest
    environment: commit-signing
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Configure SSH commit signing
        uses: shriyanss/verified-commit-action@v1
        with:
          ssh-private-key: ${{ secrets.JS_RECON_SIGNING_KEY }}
          commit-name: "js-recon-bot"
          commit-email: ${{ secrets.JS_RECON_SIGNING_EMAIL }}

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier
        run: prettier --write . --config .prettierrc

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore: prettify code" || echo "No changes to commit"
          git push
