name: Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          GH_REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          if [ ! -d "next_js" ]; then
            echo "'next_js' directory not found."
            exit 1
          fi
          cd next_js
          for dir in */ ; do
            if [ -f "${dir}Dockerfile" ]; then
              TAG=$(echo "${dir%/}" | tr '[:upper:]' '[:lower:]')
              DH_IMAGE="${DOCKER_USERNAME}/js-recon-labs:$TAG"
              GHCR_IMAGE="ghcr.io/${GH_REPO_LOWER}/js-recon-labs:$TAG"

              echo "Building and pushing to Docker Hub: ${DH_IMAGE}"
              echo "Building and pushing to GHCR: ${GHCR_IMAGE}"

              docker buildx build \
                --platform linux/amd64,linux/arm64 \
                -t "${DH_IMAGE}" \
                -t "${GHCR_IMAGE}" \
                --push \
                "${dir}"
            else
              echo "No Dockerfile found in ${dir}, skipping."
            fi
          done
