name: Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker images
        run: |
          if [ ! -d "next_js" ]; then
            echo "'next_js' directory not found."
            exit 1
          fi
          cd next_js
          for dir in */ ; do
            if [ -f "${dir}Dockerfile" ]; then
              TAG=$(echo "${dir%/}" | tr '[:upper:]' '[:lower:]')
              IMAGE_NAME="js-recon-labs:$TAG"
              echo "Building and pushing ${IMAGE_NAME}"
              docker build -t "${IMAGE_NAME}" "${dir}"
              docker push "shriyanss/${IMAGE_NAME}"
            else
              echo "No Dockerfile found in ${dir}, skipping."
            fi
          done
